### ISSUE TITLE
Mix of static and non-static methods in Session class

### ISSUE THREAD

**Issue by odan** [akrabat/rka-slim-session-middleware#18]
Hi Rob

I use this session package and I like it very much. However, from a usage perspective, the mix of static and non-static methods is quite confusing to me.

Here is an example:

```php
$session->clearAll();

\RKA\Session\regenerate();

$session->set('key', 'value');
```

The idea is to make it easier to use would be to make all static-method, non-static, e.g.

```php
$session->clearAll();

$session->regenerate();

$session->set('key', 'value');
```

I know that this is a breaking change, but it could be solved with a new major version. What do you think?

**Comment by akrabat** [comment]
Yep. That makes sense. 👍

**Comment by odan** [comment]
Ok thanks, I will create a PR as soon as possible.
