### ISSUE TITLE
Tag for Slim 3 compatibility changes

### ISSUE THREAD

**Issue by ivandokov** [akrabat/rka-slim-session-middleware#5]
Can you please create new tag for the latest update which includes Slim 3 compatibility because the package cannot be installed now without specifying `dev-master`

**Comment by akrabat** [comment]
I've just tagged `2.0.0-RC1`.

**Comment by akrabat** [comment]
If it works as expected, then I can tag `2.0.0`.

**Comment by akrabat** [comment]
2.0.0 tagged.
