### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by gracedigital** [akrabat/rka-slim-session-middleware#9]
Thinking of installing your Slim Session Middleware to store an id that is being passed in from our API clients.  We want to temporarily store this information in the event we need to log an exception or error.  Is it worth adding the middleware for this simple use case or would it be better to just add a new array element to the container?

**Comment by ivandokov** [comment]
APIs are stateless so it will not work in this case. You probably need provide token to the client and the client should return it with each request in order to keep some state between the requests. 
If you need to keep the ID for a single request you should use the container.

**Comment by akrabat** [comment]
Is this ID a client/user authentication token? If so, then as @ivandokov says, this should be stored in persistent storage such as a database and the client should send it every request in the Authorisation header.

If this is some other ID, how is it being transferred from the client? I would expect it to be in the Request, so there is no need to store it anywhere else as you can retrieve it from the Request when needed.
